name: CI
on:
  pull_request:
  workflow_dispatch:
permissions:
  checks: write
  pull-requests: write
  contents: read
  issues: write
jobs:
  ci:
    name: Continuous Integration
    uses: HeyItsGilbert/.github/.github/workflows/ModuleCI.yml@main
